name: Auto Suspend/Resume Admin + Main Backend

on:
  schedule:
    - cron: '30 18 * * *'  # Triggers at 12:00 AM IST
    - cron: '30 3 * * *'   # Triggers at 9:00 AM IST

jobs:
  manage-services:
    runs-on: ubuntu-latest
    steps:
      - name: Suspend or Resume Servers Based on IST Hour
        run: |
          HOUR=$(TZ='Asia/Kolkata' date +'%H')

          if [ "$HOUR" -eq 0 ]; then
            echo "🛑 Suspending services..."
            curl -X POST "https://api.render.com/v1/services/srv-d1l68k6mcj7s73br77lg/suspend" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

            curl -X POST "https://api.render.com/v1/services/srv-d1l64c6mcj7s73br2u3g/suspend" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
          
          elif [ "$HOUR" -eq 9 ]; then
            echo "🚀 Resuming services..."
            curl -X POST "https://api.render.com/v1/services/srv-d1l68k6mcj7s73br77lg/resume" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

            curl -X POST "https://api.render.com/v1/services/srv-d1l64c6mcj7s73br2u3g/resume" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
          
          else
            echo "⏰ Not the scheduled action time (Current IST Hour: $HOUR)."
          fi
